### ISSUE TITLE
PhotonVision Up and Running

### ISSUE THREAD

**Issue by adityapawar1** [Team3256/FRC_Offseason_2022#23]

**Comment by realjoshuau** [comment]
mDNS does not work - photonvision.local / gloworm.local / limelight.local does not work.

**Comment by 3LucasZ** [comment]
I saw it running and working at 4:00.

**Comment by realjoshuau** [comment]
More notes:
- photonvision image is broken 
- gloworm image works
- mDNS is STILL broken on wifi (for first-time setup)
- must configure team number to allow communication w robot

And then we found out the Limelight really sucks at processing images at a good latency. This may be because of the processing, but the targets do still show up, even if the stream is ~5-10 seconds  behind.

Using a raspberry pi, the install process was good & the latency & processing was better, but not good enough.

We also had to use Angry IP Scanner + `nmap -sn -vvv -oG scan_results2.txt 10.32.56.2/24` command to find the devices each time, before we configured a static IP.
